# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

source $XDG_CONFIG_HOME/shell/alias.sh
source $XDG_CONFIG_HOME/shell/functions.sh
source $XDG_CONFIG_HOME/shell/base-16-shell.sh

source $XDG_CONFIG_HOME/shell/zsh/antidote.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f "$XDG_CONFIG_HOME/shell/zsh/p10k.zsh" ]] || source "$XDG_CONFIG_HOME/shell/zsh/p10k.zsh" 

# Created by `pipx` on 2024-06-13 11:44:48
export PATH="$PATH:/Users/aaxthelm/.local/bin"
